[package]
name = "pub_sub"
version = "0.1.0"
authors = ["chriscoomber <christopher.coomber@metaswitch.com>"]

[dependencies]
futures = "0.1.13"
tokio-core = "0.1.6"
log = "0.3.6"


[dev-dependencies]
fern = "0.3.5"
time = "0.1.35"